import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image"; 
import Navbar1 from "./components/navbar";
import background from './background.jpg'; // Ensure the path is correct

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ position: 'relative' }} // Ensure the body has relative position
      >
        <Image
          src={background}
          layout="fill"
          objectFit="cover"
          style={{ zIndex: -1, position: 'absolute' ,minHeight:'120vh'}}
           // Use absolute positioning
          alt="Background Image"
        />
        <Navbar1 style={{ position: 'absolute', top: '0px', left: '0px' }} />
        {children}
      </body>
    </html>
  );
}
